In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn import tree

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/colab/data/dataVisibility.csv')
data.head()

Error Magnitude    Class    Wind Visibility
0    SS       Big  No-auto     Low         No
1    SS       Big  No-auto  Strong         No
2    MM       Big  No-auto     Low        Yes
3    LX    Medium  No-auto     Low        Yes
4    LX     Small     Auto     Low        Yes

In [ ]:
inputs = data.drop("Visibility", axis= 1)
inputs.head()

Error Magnitude    Class    Wind
0    SS       Big  No-auto     Low
1    SS       Big  No-auto  Strong
2    MM       Big  No-auto     Low
3    LX    Medium  No-auto     Low
4    LX     Small     Auto     Low

In [ ]:
data["Visibility"].head()

0     No
1     No
2    Yes
3    Yes
4    Yes
Name: Visibility, dtype: object

In [ ]:
le_error = LabelEncoder()
le_magnitude = LabelEncoder()
le_class= LabelEncoder()
le_wind = LabelEncoder()
lb_visibility = LabelEncoder()

In [ ]:
inputs['error_n'] = le_error.fit_transform(inputs['Error'])
inputs['magnitude_n'] = le_magnitude.fit_transform(inputs['Magnitude'])
inputs['class_n'] = le_class.fit_transform(inputs['Class'])
inputs['wind_n'] = le_wind.fit_transform(inputs['Wind'])

In [ ]:
inputs_n = inputs.drop(['Error','Magnitude','Class','Wind'], axis = 'columns')
inputs_n.head()

error_n  magnitude_n  class_n  wind_n
0        2            0        1       0
1        2            0        1       1
2        1            0        1       0
3        0            1        1       0
4        0            2        0       0

In [ ]:
data['Visibility'] = lb_visibility.fit_transform(data['Visibility'])
outputs = data['Visibility']
outputs.head()

0    0
1    0
2    1
3    1
4    1
Name: Visibility, dtype: int64

In [ ]:
train_features = inputs_n.iloc[:15]
train_targets = outputs[:15]
test_features = inputs_n.iloc[15:]
test_targets = outputs[15:]

In [ ]:
model = tree.DecisionTreeClassifier(criterion = 'entropy')
Tree = model.fit(train_features, train_targets)

***Test dữ liệu***


In [ ]:
prediction = Tree.predict(test_features)
print(prediction)

[0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1]


In [ ]:
print(np.array(test_targets))

[0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1]


***Test độ chính xác của dữ liệu***

In [ ]:
print("Độ chính xác của dữ liệu: ", model.score(test_features, test_targets)*100,"%")

Độ chính xác của dữ liệu:  100.0 %


***Test dữ liệu mới*** ***(Error: MM, Magnitude: Medium, Class: Auto, Wind: Low)***

In [ ]:
Tree.predict([[1,1,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])